name: Hashplay
favicon: null
layout_spectrum: 0.09832136030308902
typography_spectrum: 0.7579781899694353
title: Hashplay
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.13757406058721244
  lightness: 0.6540878831874579
  saturation: 0.15888346219435334
  rhythmicContrast: 0.6873990925960243
purpose: []
