name: Hashplay
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Hashplay
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060709'
    - '#ffffff'
    - '#29762e'
    - '#2f342d'
    - '#779fc8'
  brandStrength: 0.13757406058721244
  lightness: 0.6540878831874579
  saturation: 0.15888346219435334
  rhythmicContrast: 0.6873990925960243
purpose: []
